### PR TITLE
Removed quick commands and updated panel logic

### LINKED ISSUE #177: [PE-D] Able to delete staff when im viewing applicants list
Just a suggestion, maybe you could restrict the user such that he can only delete a staff if he is viewing staff list, same for applicants. This will prevent user from accidentally deleteing a staff or applicant.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: joshruien/ped#4

### LINKED ISSUE #180: [PE-D] Delete comment for comments with same title
I added a comment with the same title and when i tried to delete comment it deleted my comment instead of the hardcoded one. This should be mentioned in the UG if this is your intention.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: joshruien/ped#7

### LINKED ISSUE #184: [PE-D] addcomment throws storage error
`Could not save data to file: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.eva.storage.JsonStaffDatabase["staffs"]->java.util.ArrayList[0]->com.eva.storage.JsonAdaptedStaff["comments"]->java.util.ArrayList[2]->com.eva.storage.JsonAdaptedComment["getCommentDetails()"])
`

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: cupofjoee/ped#5

### LINKED ISSUE #206: [PE-D] Gaps between correct command format and that given in error message
When I type "editstaff 7 c/ti/leave request d/12-3-2000", this message appears:

comment: Adds or delete comment to personTo add comment: key in 'addComment INDEX <s-/a-> ti/TITLE d/DATE desc/DESCRIPTION'
To delete, key in 'deleteComment INDEX <s-/a-> ti/TITLE_TO_DELETE' 
To edit, key in editComment INDEX <s-/a-> ti/TITLE d/DATE desc/NEW_DESCRIPTION

But when I try to follow the format as shown in the screenshot, it is an invalid command because it is actually "addcomment ...." as per the UG but because I haven't read the comment section of the UG at the point, I thought the addcommand feature of your app was broken so it would be good to ensure that all error messages in the app provide correct examples.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JoeyToh/ped#9

### LINKED ISSUE #209: [PE-D] Cannot understand rationale to have the normal commands and the quick commands
Sorry but I don't really understand why the shorter commands are for experienced users. If I'm a beginner and I realise that there are quick commands available, I would just use these quick commands instead of having to type more for the normal commands. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: JoeyToh/ped#12

### PR DESCRIPTION
**Pull request by IsaacTin**

### CODE REVIEW

File: src/main/java/com/eva/logic/commands/AddApplicationCommand.java [hunk 1]
```diff
@@ -23,6 +28,8 @@
             + "Example: " + COMMAND_WORD + " "
             + "src\\main\\java\\com\\eva\\logic\\parser\\resume.txt \n"
             + "or if you would like to scan a sample resume: addapplication 1 sample";
+    public static final String MESSAGE_WRONG_PANEL = "Please switch to applicant list panel "
+            + "via 'list a-' to add application of applicant";
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddApplicationCommand.java:32]: Since they're able to add an application from a profile perhaps you should include that in the message as well? Maybelike "Please switch to applicant list panel (list a-) or view applicant profile panel to add application to applicant."

File: src/main/java/com/eva/logic/commands/AddApplicationCommand.java [hunk 2]
```diff
@@ -44,6 +51,10 @@ public AddApplicationCommand(Index index, Application application) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        PanelState panelState = model.getPanelState();
+        if (!panelState.equals(APPLICANT_PROFILE) && !panelState.equals(APPLICANT_LIST)) {
+            throw new CommandException(MESSAGE_WRONG_PANEL);
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddApplicationCommand.java]: We should have a standardized error message when having a wrong panel related error (refer to viewCommand).
The error message can be formatted as such:
String.format(Messages.MESSAGE_INVALID_COMMAND_AT_PANEL, MESSAGE_WRONG_PANEL))

File: src/main/java/com/eva/logic/commands/AddApplicationCommand.java [hunk 3]
```diff
@@ -53,6 +64,16 @@ public CommandResult execute(Model model) throws CommandException {
 
         Applicant applicantToUpdate = lastShownList.get(index.getZeroBased());
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddApplicationCommand.java:72]: For this if an invalid index is entered is the error is caught in mainWindow? If it is then i'll change view command to take out the try catch cause it'll make the code look neater

File: src/main/java/com/eva/logic/commands/AddApplicationCommand.java [hunk 4]
```diff
@@ -53,6 +64,16 @@ public CommandResult execute(Model model) throws CommandException {
...
         model.addApplicantApplication(applicantToUpdate, applicationToAdd);
-        return new CommandResult(String.format(MESSAGE_SUCCESS, applicantToUpdate.getName()));
+        if (panelState.equals(APPLICANT_LIST)) {
+            model.updateFilteredApplicantList(PREDICATE_SHOW_ALL_APPLICANTS);
+        } else if (panelState.equals(APPLICANT_PROFILE)) {
+            model.updateFilteredApplicantList(PREDICATE_SHOW_ALL_APPLICANTS);
+            Applicant applicantToView = lastShownList.get(index.getZeroBased());
+            model.setCurrentViewApplicant(new CurrentViewApplicant(applicantToView));
+        }
+        model.setPanelState(APPLICANT_LIST);
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddApplicationCommand.java]: not sure if you want the expected behavior to be to bring the user to the list view if the user adds the application to the applicant on its profile panel.

File: src/main/java/com/eva/logic/commands/AddCommentCommand.java [hunk 5]
```diff
@@ -27,66 +34,76 @@
...
+    public AddCommentCommand(Index index, CommentCommand.CommentPersonDescriptor commentPersonDescriptor) {
         super(index, commentPersonDescriptor);
-        this.personType = personType;
     }
 
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-        //for now is staff because we only working with staff for now
+        PanelState personType = model.getPanelState();
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddCommentCommand.java]: Should change the name to panelState or currentPanel or something along those lines

File: src/main/java/com/eva/logic/commands/AddCommentCommand.java [hunk 6]
```diff
@@ -27,66 +34,76 @@
...
+                model.setStaff((Staff) personToEdit, (Staff) editedPerson);
+                model.updateFilteredStaffList(PREDICATE_SHOW_ALL_STAFFS);
+                Staff staffToView = (Staff) lastShownList.get(index.getZeroBased());
+                model.setCurrentViewStaff(new CurrentViewStaff(staffToView, index));
+            } else if (personType.equals(APPLICANT_PROFILE)) {
+                model.setApplicant((Applicant) personToEdit, (Applicant) editedPerson);
+                model.updateFilteredApplicantList(PREDICATE_SHOW_ALL_APPLICANTS);
+                Applicant applicantToView = (Applicant) lastShownList.get(index.getZeroBased());
+                model.setCurrentViewApplicant(new CurrentViewApplicant(applicantToView));
+            }
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddCommentCommand.java]: maybe using a switch would be more presentable

File: src/main/java/com/eva/logic/commands/AddLeaveCommand.java [hunk 7]
```diff
@@ -37,6 +41,8 @@
     public static final String MESSAGE_SUCCESS = "Leave recorded: %1$s took %2$s";
     public static final String MESSAGE_DUPLICATE_RECORD = "This staff: %s "
             + "has overlapping leave date during this period: %s";
+    public static final String MESSAGE_WRONG_PANEL = "Please switch to staff list panel "
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddLeaveCommand.java:44]: same as add application

File: src/main/java/com/eva/logic/commands/AddLeaveCommand.java [hunk 8]
```diff
@@ -53,9 +59,12 @@ public AddLeaveCommand(Index targetIndex, List<Leave> leave) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        PanelState panelState = model.getPanelState();
+        if (!panelState.equals(STAFF_LIST) && !panelState.equals(STAFF_PROFILE)) {
+            throw new CommandException(MESSAGE_WRONG_PANEL);
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/AddLeaveCommand.java]: same issue as add application

File: src/main/java/com/eva/logic/commands/DeleteApplicationCommand.java [hunk 9]
```diff
@@ -1,23 +1,27 @@
...
 
 public class DeleteApplicationCommand extends Command {
-    public static final String COMMAND_WORD = "delapplication";
+    public static final String COMMAND_WORD = "delapp";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Deletes the applicant's application identified by the index number used by the applicant list.\n"
             + "Parameters: INDEX (must be a positive integer)\n"
             + "Example: " + COMMAND_WORD + " 1";
+    public static final String MESSAGE_WRONG_PANEL = "Please switch to applicant list panel "
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/DeleteApplicationCommand.java:26]: same issue

File: src/main/java/com/eva/logic/commands/DeleteApplicationCommand.java [hunk 10]
```diff
@@ -37,6 +41,10 @@ public DeleteApplicationCommand(Index targetIndex) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        PanelState panelState = model.getPanelState();
+        if (!panelState.equals(APPLICANT_LIST)) {
+            throw new CommandException(MESSAGE_WRONG_PANEL);
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/DeleteApplicationCommand.java]: same issue

File: src/main/java/com/eva/logic/commands/DeleteApplicantCommand.java [hunk 11]
```diff
@@ -40,6 +44,10 @@ public DeleteApplicantCommand(Index targetIndex) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        PanelState panelState = model.getPanelState();
+        if (!panelState.equals(APPLICANT_LIST)) {
+            throw new CommandException(MESSAGE_WRONG_PANEL);
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/DeleteApplicantCommand.java]: same issue

File: src/main/java/com/eva/logic/commands/DeleteCommentCommand.java [hunk 12]
```diff
@@ -73,14 +76,25 @@ public CommandResult execute(Model model) throws CommandException {
...
                 model.setStaff((Staff) personToEdit, (Staff) editedPerson);
                 model.updateFilteredStaffList(PREDICATE_SHOW_ALL_STAFFS);
-            } else {
+                Staff staffToView = (Staff) lastShownList.get(index.getZeroBased());
+                model.setCurrentViewStaff(new CurrentViewStaff(staffToView, index));
+            } else if (personType.equals(APPLICANT_PROFILE)) {
                 model.setApplicant((Applicant) personToEdit, (Applicant) editedPerson);
                 model.updateFilteredApplicantList(PREDICATE_SHOW_ALL_APPLICANTS);
+                Applicant applicantToView = (Applicant) lastShownList.get(index.getZeroBased());
+                model.setCurrentViewApplicant(new CurrentViewApplicant(applicantToView));
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/DeleteCommentCommand.java]: switch

File: src/main/java/com/eva/logic/commands/DeleteLeaveCommand.java [hunk 13]
```diff
@@ -33,6 +37,8 @@
     public static final String MESSAGE_SUCCESS = "Deleted Leave: %1$s from %2$s";
     public static final String MESSAGE_NO_RECORD = "This staff: %s "
             + "has not taken any leave during any period containing this date: %s";
+    public static final String MESSAGE_WRONG_PANEL = "Please switch to staff list panel "
+            + "via 'list s-' to delete leave of staff";
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/DeleteLeaveCommand.java:41]: same issue

File: src/main/java/com/eva/logic/commands/DeleteLeaveCommand.java [hunk 14]
```diff
@@ -50,7 +56,10 @@ public DeleteLeaveCommand(Index targetIndex, LocalDate date) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-
+        PanelState panelState = model.getPanelState();
+        if (!panelState.equals(STAFF_LIST) && !panelState.equals(STAFF_PROFILE)) {
+            throw new CommandException(MESSAGE_WRONG_PANEL);
```
Comment (Ben-Hanan) [inline src/main/java/com/eva/logic/commands/DeleteLeaveCommand.java]: same issue

File: src/main/java/com/eva/logic/commands/AddApplicationCommand.java [hunk 15]
```diff
@@ -44,6 +51,10 @@ public AddApplicationCommand(Index index, Application application) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        PanelState panelState = model.getPanelState();
+        if (!panelState.equals(APPLICANT_PROFILE) && !panelState.equals(APPLICANT_LIST)) {
```
Comment (Nikhilalalalala) [inline src/main/java/com/eva/logic/commands/AddApplicationCommand.java:55]: Does this allow the case where I am viewing Applicant A but I can add application for Applicant B?

File: src/main/java/com/eva/logic/commands/AddApplicationCommand.java (hunk 3 above)
Comment (Nikhilalalalala) [reply src/main/java/com/eva/logic/commands/AddApplicationCommand.java:72]: The error is caught in lines 61 to 63, in this method itself. If thats the error youre looking for.

**Comment by Ben-Hanan** [comment]
LGTM
